### ISSUE TITLE
Can't see other devices on LAN

### ISSUE THREAD

**Issue by kernitus** [trebleshot/android#18]
When two devices are connected to the same WiFi network (i.e. one with a router, not a hotspot), neither device can see the other on the nearby devices list, even after scan is completed a couple of times. I have seen this happen on more than one WiFi network, even home networks (which do not have restrictions on the LAN).

**Comment by velitasali** [comment]
Hi. Poor connections may also lead this problem. There is only 300ms before TrebleShot gives up. A fast router is always recommended. I know it's a bit frustrating to hear but you should be close to the router when devices are scanning. It's the first time I hear something like though.

Normally 300ms is just a ping time given for each ip address tested and it's pretty much okay most of the time.
After a successful ping, TrebleShot tries to connect with a much longer time lapse to that ip to check if it's a TrebleShot running device. So after devices find each other, router should not be any problem. Let me know what you think. Thanks.

**Comment by gvlfm78** [comment]
I mean to say that I have tried this on more than one network. But I will try it again on more networks to see if this is a recurring problem or just happens rarely because of a bad connection.

**Comment by velitasali** [comment]
I could increase the 300ms of ping time but it will make scanning process longer, but still maybe an option in setting that change that seems reasonable. Thanks.

**Comment by ccaapton** [comment]
Does TrebleShot use the Network Service Discovery(https://developer.android.com/training/connect-devices-wirelessly/nsd.html) to find the peers?

**Comment by velitasali** [comment]
@ccaapton I am deeply sorry for the late reply. I just realized I forgot to hit enter button. No, it does not.

**Comment by gvlfm78** [comment]
btw @velitasali I still have this issue every so often, although it happens mostly in big networks that have many routers, even if both devices are connected to the same router.

**Comment by velitasali** [comment]
@gvlfm78 you should help me on this to fix issues. Can you provide me these informations :);

1- Does you IP change when you go across in the building?
2- Do you try to scan devices when the problem occurs?
3- Does local networking work like Windows SMB connection across devicez or a printer connected to the same network?

**Comment by gvlfm78** [comment]
1. The IP remains the same
2. I manually initiate a scan for devices on both devices
3. I don't know exactly what you mean by this but printers do appear on the network.
I should add that sometimes the other device is found immediately whilst other times it cannot be found even after multiple attempts. I have also tried this with a few different devices.

**Comment by velitasali** [comment]
If the IP address remains the same, it must be something else causing this. Could you use any other application which offers network connectivity with another device to make sure if it is something we can fix?

**Comment by gvlfm78** [comment]
I have found that this happens only with one specific device. Through LAN, WiFi direct or Hotspot it cannot find and is not findable from other devices. I'm not sure what is causing this, maybe some hidden setting in the phone? It is using almost-AOSP Android Marshmallow.

**Comment by velitasali** [comment]
@gvlfm78 I have encountered the same issue with my friend's phone. Today, I will be digging up why it happpens. Does it work normally after when one discovers another successfully?

**Comment by gvlfm78** [comment]
Well it seems neither phone can find each other. I need to try with that phone and a different phone to see if it is the combination of phones or just that phone.

Hotspots can still be found, though.

**Comment by velitasali** [comment]
I just implemented nsd feature which reduces the time for discovery and is more reliable, yet not removed old one as manual search might be needed.

**Comment by gvlfm78** [comment]
Ok @velitasali I have just tried with that one device which seems to have problems connecting. On the newest TrebleShot version, with NSD enabled or disabled, on LAN, hotspot or WiFi direct it is still unable to see any other devices or be seen by any other devices. I have no idea what the issue is...

On the other hand, the new NSD did help with devices that already worked, as they are now found faster while on the network.

**Comment by velitasali** [comment]
@gvlfm78 At least I would except NSD to fix the issue as it is a service that relies on an universal API for multi-platforms. Does the device have any app like batter saver because apps like that sometimes kill background services of applications?

**Comment by gvlfm78** [comment]
Well, I'd need to check but do you mean some 3rd party app or Android Doze?

**Comment by velitasali** [comment]
@gvlfm78 3rd apps or the ones that come preinstalled like "asus power manager"

**Comment by gvlfm78** [comment]
That device does not appear to have any such apps

**Comment by velitasali** [comment]
@gvlfm78 Hi, could you provide brand and model name of the device?

**Comment by gvlfm78** [comment]
The device that is not seen by any other device is a THL T9 PRO. It's a terrible device but the OS on it seems to be extremely close to stock Android MM.

**Comment by velitasali** [comment]
@gvlfm78 It could be device specific. I will inform if I find a solution.
